# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4491bd2272d6cfcf7d71ec08c3176b1a7b8fa27baf42d825e8a599babeed079676fb140bfdf74a2688e1f6f7e6ce7aaa7186f3d224632a7966e704b18f3277de

test:
  secret_key_base: 6cbebe1a35814631cfcfcd08d93f4bdd0c0721cee9b2ce5a0b7a364fd65c6d5c287e21c5c5afbacafcf571b79a281d19531935f1d44dee0957d8297db598ba58

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
